name: LAB5

on:
  push:
    branches:
      - master
jobs:   
  windows_build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: pip installation
      run: python -m pip install --upgrade pip
    - name: unit test
      run: python -m unittest circle.py
    - name: unit test
      run: python -m unittest rectangle.py
    - name: unit test
      run: python -m unittest square.py
    - name: unit test
      run: python -m unittest triangle.py
		
  linux_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: pip installation
      run: python -m pip install --upgrade pip
    - name: unit test
      run: python -m unittest circle.py
    - name: unit test
      run: python -m unittest rectangle.py
    - name: unit test
      run: python -m unittest square.py
    - name: unit test
      run: python -m unittest triangle.py
