name: LAB5

on:
  push:
    branches:
      - master
jobs:   
  windows_build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: pip installation
      run: |
        python -m pip install --upgrade pip
    - name: unit test circle.py
      run: |
        python -m unittest circle.py
      continue-on-error: true
    - name: unit test rectangle.py
      run: |
        python -m unittest rectangle.py
      continue-on-error: true
    - name: unit test square.py
      run: |
        python -m unittest square.py
      continue-on-error: true
    - name: unit test triangle.py
      run: |
        python -m unittest triangle.py
      continue-on-error: true

  linux_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: pip installation
      run: |
        python -m pip install --upgrade pip
    - name: unit test circle.py
      run: |
        python -m unittest circle.py
      continue-on-error: true
    - name: unit test rectangle.py
      run: |
        python -m unittest rectangle.py
      continue-on-error: true
    - name: unit test square.py
      run: |
        python -m unittest square.py
      continue-on-error: true
    - name: unit test triangle.py
      run: |
        python -m unittest triangle.py
      continue-on-error: true
